### ISSUE TITLE
服务器端渲染如何兼容

### ISSUE THREAD

**Issue by F3n67u** [lanistor/react-keeper#51]
react-keeper是不支持服务器端渲染的，但是我们的项目目前有服务器端渲染的需要，对于服务器端渲染，有什么推荐的兼容解决方案吗？

**Comment by vifird** [comment]
@F3n67u 服务端渲染我们是有计划支持的，详细可以邮件沟通：vifirde@gmail.com。

**Comment by vifird** [comment]
Good one: [next version 3](https://github.com/vifird/react-keeper/issues/64)
