### ISSUE TITLE
restful api 多参数在安卓下失效

### ISSUE THREAD

**Issue by lgyytm** [lanistor/react-keeper#76]
` <Route  path='/agencyaction(/:Unid)(/:index)(/:isQsbwd)' component={PageAgencyaction} />`
`Control.go('/home/agency/agencyaction/' + Unid + '/' + index + '/' + isQsbwd);`
只获取到了Unid，index和isQsbwd都为undefined,
请问该怎么办

**Comment by vifird** [comment]
@lgyytm 可否贴下完整代码？我们未能复现这个问题。
